client: client.c
	gcc -Wall -Werror -o client client.c

server: server.c
	gcc -Wall -Werror -o server server.c

http_start: http_start.c
	gcc -Wall -Werror -o http_start http_start.c

clean:
	rm client server
